version: '2'
services:
    xclr8-mongodb:
        container_name: xclr8-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/xclr8/mongodb/:/data/db/
